/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aulav2.view.Cliente;

import br.com.aulav2.view.Cliente.ClienteFisica;

import br.com.aulav2.view.Cliente.ClienteJuridica;
 
public class CadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpCadastroCliente = new javax.swing.JPanel();
        Pessoafisica = new javax.swing.JRadioButton();
        Pessoajuridica = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes");

        Pessoafisica.setText("Pessoa Física");
        Pessoafisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PessoafisicaActionPerformed(evt);
            }
        });

        Pessoajuridica.setText("Pessoa Jurídica");
        Pessoajuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PessoajuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdpCadastroClienteLayout = new javax.swing.GroupLayout(jdpCadastroCliente);
        jdpCadastroCliente.setLayout(jdpCadastroClienteLayout);
        jdpCadastroClienteLayout.setHorizontalGroup(
            jdpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pessoafisica)
                .addGap(92, 92, 92)
                .addComponent(Pessoajuridica)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jdpCadastroClienteLayout.setVerticalGroup(
            jdpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pessoafisica)
                    .addComponent(Pessoajuridica))
                .addContainerGap(445, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PessoafisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PessoafisicaActionPerformed
    ClienteFisica obj = new ClienteFisica();
        jdpCadastroCliente.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_PessoafisicaActionPerformed

    private void PessoajuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PessoajuridicaActionPerformed
    ClienteJuridica = new ClienteJuridica();
        jdpCadastroCliente.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_PessoajuridicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Pessoafisica;
    private javax.swing.JRadioButton Pessoajuridica;
    private javax.swing.JPanel jdpCadastroCliente;
    // End of variables declaration//GEN-END:variables
}
